### ISSUE TITLE
Fehler wenn 2 Messwerte den gleichen Field-Namen haben

### ISSUE THREAD

**Issue by Oessi87** [solectrus/power-splitter#102]
Hallo,
ich habe 2 Shellys, um den Verbrauch der Wärmepumpe sowie für das E-Auto zu erfassen.
Dadurch habe ich die DB-Werte **KLIMA:power** sowie **WALLBOX:power**.
Leider führt dies im Power-Splitter zu einem Problem, da hier nur der Feldname beachtet wird und somit der Wert für die Wärmepumpe mit dem Wert der Wallbox überschrieben wird.

Die Problematische Stelle liegt in der **lib/flux/extractor.rb** in der Funktion **extract_and_transform_data**
Vielleicht wäre es möglich den Measurement-Name hier auch zu beachten?

**Comment by ledermann** [comment]
Danke für den Fehlerreport und die mitgelieferte Analyse, super! 👍 

Ich habe das gerade korrigiert. Du kannst das direkt ausprobieren, in dem du den Power-Splitter in deinem Compose-File von `latest` auf `develop` wechselst. Danach `docker compose pull && docker compose up -d`.

Wenn es bei dir damit funktioniert, mache ich ein neues Release für den Power-Splitter.

**Comment by Oessi87** [comment]
Habe gerade die develop-Version getestet und bei mir sieht es gut aus.
Vielen Dank für die schnelle Reaktion.

**Comment by ledermann** [comment]
@Oessi87 Danke für die Rückmeldung, ich habe jetzt das neue Release v0.5.1 erstellt. Du kannst also wieder auf `latest` wechseln.
