### ISSUE TITLE
Neuberechnung historischer Werte?

### ISSUE THREAD

**Issue by Choumiko** [solectrus/power-splitter#119]
Hallo,

gibt es eine Möglichkeit die (historischen) Werte neu berechnen zu lassen? Ich habe bei der Einrichtung des Power-Splitters ein paar Fehler in der Konfiguration gemacht und nun ist das E-Auto bis zum Tag der Installation mit 100% PV-Strom gefahren und in der Jahresübersicht "fehlen" ca 50€ an Netzbezugskosten.

**Comment by ledermann** [comment]
Ja, die Möglichkeit gibt es:

```
docker compose kill --signal USR1 power-splitter
```

**Comment by Choumiko** [comment]
Super, danke schön.

Danach
`docker compose up -d`
und es läuft wieder.

**Comment by ledermann** [comment]
Ein erneutes `compose up` ist eigentlich nicht nötig. Der "Kill-Befehl" ist gar nicht so drastisch, wie er sich anhört. Es wird nur ein benutzerdefiniertes Signal (`USR1`) an den Container geschickt, der darauf reagiert, ohne sich zu beenden. Nach dem Rebuild wechselt der Container wieder in eine Endlosschleife und bearbeitet die aktuellen Daten, die ja permanent hereinkommen.
