### ISSUE TITLE
[BUG] Custom sensors not correctly detected by INFLUX_EXCLUDE_FROM_HOUSE_POWER

### ISSUE THREAD

**Issue by unclej84** [solectrus/power-splitter#154]
I just tried to start the develop build with the new custom sensors and received an error directly at the container start:

bundler: failed to load command: app.rb (app.rb)
Power Splitter for SOLECTRUS, Version develop, built at 2024-12-11 15:22:15 +0100
Using Ruby 3.3.6 on platform x86_64-linux-musl
Copyright (c) 2024 Georg Ledermann <georg@ledermann.dev>
https://github.com/solectrus/power-splitter

Accessing InfluxDB at http://influxdb:8086, bucket my-solectrus-bucket
Sensor initialization started
  - Sensor 'grid_import_power' mapped to 'SENEC:grid_power_plus'
  - Sensor 'house_power' mapped to 'SENEC:house_power'
  - Sensor 'wallbox_power' mapped to 'SENEC:wallbox_charge_power'
  - Sensor 'battery_charging_power' mapped to 'SENEC:bat_power_plus'
/power-splitter/lib/config.rb:158:in \`define_exclude_from_house_power': Invalid sensor name in INFLUX_EXCLUDE_FROM_HOUSE_POWER: CUSTOM_POWER_01,CUSTOM_POWER_02,CUSTOM_POWER_06,CUSTOM_POWER_08 (Config::Error)
        from /power-splitter/lib/config.rb:105:in \`init_sensors'
        from /power-splitter/lib/config.rb:34:in \`initialize'
        from app.rb:28:in \`new'
        from app.rb:28:in \`<top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in \`load'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in \`kernel_load'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:23:in \`run'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:456:in \`exec'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/command.rb:28:in \`run'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in \`invoke_command'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor.rb:527:in \`dispatch'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:35:in \`dispatch'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/base.rb:584:in \`start'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:29:in \`start'
        from /usr/local/bundle/gems/bundler-2.5.23/exe/bundle:28:in \`block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/friendly_errors.rb:117:in \`with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.5.23/exe/bundle:20:in \`<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in \`load'
        from /usr/local/bundle/bin/bundle:25:in \`<main>'

My .env contains this relevant lines:
`
INFLUX_SENSOR_CUSTOM_POWER_01=heatpump:power
INFLUX_SENSOR_CUSTOM_POWER_02=freezer:power
INFLUX_SENSOR_CUSTOM_POWER_03=ac_bedroom:power
INFLUX_SENSOR_CUSTOM_POWER_04=ac_veranda:power
INFLUX_SENSOR_CUSTOM_POWER_05=ac_living_room:power
INFLUX_SENSOR_CUSTOM_POWER_06=fridge_basement:power
INFLUX_SENSOR_CUSTOM_POWER_07=microwave:power
INFLUX_SENSOR_CUSTOM_POWER_08=well_pump:power
INFLUX_SENSOR_CUSTOM_POWER_09=washing_machine:power
INFLUX_SENSOR_CUSTOM_POWER_10=dryer:power
INFLUX_EXCLUDE_FROM_HOUSE_POWER=CUSTOM_POWER_01,CUSTOM_POWER_02,CUSTOM_POWER_06,CUSTOM_POWER_08
`

I suspect the problem somewhere [here](https://github.com/solectrus/power-splitter/blob/7fb8099ae9ea0686c144c36a39e552aaed969066/lib/config.rb#L135) as the sensor is not detected `define_sensor` function (line 141)

**Comment by unclej84** [comment]
My mistake - forgot to add the environment variables also to the power splitter container

**Comment by ledermann** [comment]
You need to switch the PowerSplitter to `develop`.

**Comment by patricknitsch** [comment]
Danke Georg!
