### ISSUE TITLE
Missing default value for further calls of power_value function

### ISSUE THREAD

**Issue by unclej84** [solectrus/power-splitter#156]
Same issue in [split_power](https://github.com/solectrus/power-splitter/blob/c0bd7691f9a8aa59731642eca534f6c201c6d700/lib/processor.rb#L104) for the other sensors - maybe the default value in `def power_value` should be changed from nil to 0.0 like it was before

_Originally posted by @unclej84 in https://github.com/solectrus/power-splitter/issues/155#issuecomment-2536693772_

**Comment by ledermann** [comment]
Please post the backtrace.

**Comment by unclej84** [comment]
#<Thread:0x00007b7e793fcde8 /power-splitter/lib/loop.rb:62 run> terminated with exception (report_on_exception is true):
/power-splitter/lib/splitter.rb:29:in `call': undefined method `positive?' for nil (NoMethodError)

    if remaining.positive? && wallbox_power.positive?
                ^^^^^^^^^^
        from /power-splitter/lib/processor.rb:125:in `split_power'
        from /power-splitter/lib/processor.rb:14:in `block in call'
        from /power-splitter/lib/processor.rb:14:in `each'
        from /power-splitter/lib/processor.rb:14:in `reduce'
        from /power-splitter/lib/processor.rb:14:in `call'
        from /power-splitter/lib/loop.rb:115:in `process_day'
        from /power-splitter/lib/loop.rb:100:in `process_historical_data'
        from /power-splitter/lib/loop.rb:63:in `block in start_thread'
bundler: failed to load command: app.rb (app.rb)
/power-splitter/lib/splitter.rb:29:in `call': undefined method `positive?' for nil (NoMethodError)

    if remaining.positive? && wallbox_power.positive?
                ^^^^^^^^^^
        from /power-splitter/lib/processor.rb:125:in `split_power'
        from /power-splitter/lib/processor.rb:14:in `block in call'
        from /power-splitter/lib/processor.rb:14:in `each'
        from /power-splitter/lib/processor.rb:14:in `reduce'
        from /power-splitter/lib/processor.rb:14:in `call'
        from /power-splitter/lib/loop.rb:115:in `process_day'
        from /power-splitter/lib/loop.rb:100:in `process_historical_data'
        from /power-splitter/lib/loop.rb:63:in `block in start_thread'

**Comment by ledermann** [comment]
Just made another fix. The main reason I don’t want to turn every `nil` into a `0` is data minimization. InfluxDB should only store what is truly necessary.
