### ISSUE TITLE
Timeout-Error when triggering recalcultation

### ISSUE THREAD

**Issue by unclej84** [solectrus/power-splitter#158]
When I try to recalculate historical values via `docker compose kill --signal USR1 power-splitter` the container crashes after some time. I have to recreate the service completely and run the kill command several times until it succeeds and start recalculation after deleting the old values. Everytime only a chunk of values gets deleted before the error. Might be due to bad performance of the Influx db. Alternatively I run the delete command directly in the influx container via cli which also takes a few minutes to complete but without error in one go.

This is the error I get in the logs:

--- Deleting all records from InfluxDB measurement 'power_splitter'
bundler: failed to load command: app.rb (app.rb)
/usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/default_api.rb:109:in `rescue in _request': Net::ReadTimeout with #<TCPSocket:(closed)> (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/default_api.rb:108:in `_request'
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/default_api.rb:54:in `_request_json'
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/delete_api.rb:67:in `_delete'
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/delete_api.rb:53:in `delete'
        from /power-splitter/lib/flux/deleter.rb:16:in `delete'
        from /power-splitter/lib/flux/deleter.rb:6:in `delete_measurement'
        from /power-splitter/lib/influx_push.rb:35:in `delete_measurement'
        from /power-splitter/lib/loop.rb:121:in `delete_all'
        from /power-splitter/lib/loop.rb:26:in `block in start'
        from <internal:kernel>:187:in `loop'
        from /power-splitter/lib/loop.rb:17:in `start'
        from app.rb:30:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:456:in `exec'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:35:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:29:in `start'
        from /usr/local/bundle/gems/bundler-2.5.23/exe/bundle:28:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.5.23/exe/bundle:20:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
/usr/local/lib/ruby/3.3.0/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
        from /usr/local/lib/ruby/3.3.0/net/protocol.rb:199:in `readuntil'
        from /usr/local/lib/ruby/3.3.0/net/protocol.rb:209:in `readline'
        from /usr/local/lib/ruby/3.3.0/net/http/response.rb:158:in `read_status_line'
        from /usr/local/lib/ruby/3.3.0/net/http/response.rb:147:in `read_new'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:2342:in `block in transport_request'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:2333:in `catch'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:2333:in `transport_request'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:2306:in `request'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:2299:in `block in request'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1570:in `start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:2297:in `request'
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/default_api.rb:82:in `_request'
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/default_api.rb:54:in `_request_json'
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/delete_api.rb:67:in `_delete'
        from /usr/local/bundle/gems/influxdb-client-3.2.0/lib/influxdb2/client/delete_api.rb:53:in `delete'
        from /power-splitter/lib/flux/deleter.rb:16:in `delete'
        from /power-splitter/lib/flux/deleter.rb:6:in `delete_measurement'
        from /power-splitter/lib/influx_push.rb:35:in `delete_measurement'
        from /power-splitter/lib/loop.rb:121:in `delete_all'
        from /power-splitter/lib/loop.rb:26:in `block in start'
        from <internal:kernel>:187:in `loop'
        from /power-splitter/lib/loop.rb:17:in `start'
        from app.rb:30:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:456:in `exec'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:35:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/cli.rb:29:in `start'
        from /usr/local/bundle/gems/bundler-2.5.23/exe/bundle:28:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.23/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.5.23/exe/bundle:20:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'

**Comment by ledermann** [comment]
> [...] via cli which also takes a few minutes to complete [...]

That's quite a long time. In my experience (on a Hetzner cloud machine), deletion only takes a few seconds (with 4 years of data).

However, I have just increased the timeout to 5 minutes so that the error should no longer occur.

**Comment by unclej84** [comment]
I guess the hardware of the systems make a huge difference here. I guess Hetzner has running SSDs and quite modern CPUs.
I have it running on Docker inside an Ubuntu VM (4Cores and 5GB RAM) on a Synology DS716+II (Intel Celeron N3160 4 Core 1,6Ghz with 8GB RAM and NAS HDD in RAID 1). So especially the HDDs might be the bottle neck here.

**Comment by ledermann** [comment]
Totally agree: SSD > HDD. That’s probably the reason.
